export const GET_LIST_COUSRSE = "GET_LIST_COUSRSE";
export const GET_LIST_COUSRSE_DETAIL = "GET_LIST_COUSRSE_DETAIL";
export const GET_CATA_COUSRSE = "GET_CATA_COUSRSE";
export const LAYDS_GV= "LAYDS_GV";
export const GET_LIST_CATEGORY ="GET_LIST_CATEGORY";


